"""
const.py
const for onvif
"""
ATTR_PTZ_UNSUPPORTED = "ptz_unsupported"
ATTR_PTZ_PRESETS_UNSUPPORTED = "ptz_presets_unsupported"
ATTR_PTZ_RELATIVEMOVE_UNSUPPORTED = "ptz_relative_move_unsupported"
ATTR_PTZ_ABSOLUTE_UNSUPPORTED = "ptz_absolute_move_unsupported"

DEFAULT_NAME = "ONVIF Camera"
DEFAULT_PORT = 5000
DEFAULT_USERNAME = "admin"
DEFAULT_PASSWORD = "888888"
DEFAULT_ARGUMENTS = "-pred 1"
CONF_RTSP_TRANSPORT = "rtsp_transport"
RTSP_TRANSPORT_UDP = "UDP"
RTSP_TRANSPORT_HTTP = "HTTP"
RTSP_TRANSPORT_RTSP = "RTSP"

DEFAULT_PROFILE_IDX = 0
CONF_CONTINUOUS_TIMEOUT_COMPLIANCE = "continuous_timeout_compliance"

CONF_PROFILE_IDX = "profile"
CONF_PRESETS_INPUT_SELECT_NAME = "presets_list_name"

SERVICE_PTZ_ADVANCED_MOVE = "onvif_ptz_advanced_move"
SERVICE_PTZ_MOVE = "onvif_ptz_move"
SERVICE_ONVIF_CMD_REBOOT = "onvif_cmd_reboot"
ATTR_MOVE_MODE = "move_mode"
CONTINUOUS_MOVE = "ContinuousMove"
RELATIVE_MOVE = "RelativeMove"
ABSOLUTE_MOVE = "AbsoluteMove"
STOP_MOVE = "Stop"
PTZ_NONE = "NONE"
ATTR_PTZ_VECTOR = "ptz_vector"
ATTR_SPEED_VECTOR = "speed_vector"
ATTR_PAN = "pan"
ATTR_TILT = "tilt"
ATTR_ZOOM = "zoom"
ATTR_DISTANCE = "distance"
ATTR_SPEED = "speed"
ATTR_CONTINUOUS_DURATION = "continuous_timeout"
DIR_UP = "UP"
DIR_DOWN = "DOWN"
DIR_LEFT = "LEFT"
DIR_RIGHT = "RIGHT"
ZOOM_OUT = "ZOOM_OUT"
ZOOM_IN = "ZOOM_IN"

SERVICE_PTZ_PRESET = "onvif_ptz_preset"
ATTR_PRESET_OPERATION = "preset_operation"
GET_PRESETS = "GetPresets"
SET_PRESET = "SetPreset"
GOTO_PRESET = "GotoPreset"
ATTR_PRESET_NAME = "preset_name"
ATTR_PRESET_TOKEN = "preset_token"
GOTO_HOME = "GotoHomePosition"
SET_HOME = "SetHomePosition"
ONVIF_DATA = "onvif"
ENTITIES = "entities"

INFO_STREAM_URI = "onvif_stream_uri"
